Decorate a class
ahzamir/OOP-school-library pull request #2
Opened 2022-08-03 19:08 UTC by ahzamir

### in this pull request I have used Inheritance and Decorator to decorate my classes according to these requirements:

2022-08-03 20:01 UTC, BenMukebo requested changes
### Hi @ahzamir,

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight 💪🏻
- GitHub flow was correctly used.  ✔️
- Descriptive PR ✔️
- No linter errors ✔️
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_


- [ ] Great job using the Microverse templates to write your README l file 👍🏻  but I think you can customize it to your project in order to make it descriptive and more professional. A professional README file should have a project title, project description, list of technology used in the project, instructions to set the project up locally,  and a screenshot of your project. please refer to this [template](https://github.com/microverseinc/readme-template), you can copy and paste the content but remember to customize it to your project.

- The README file It is the first file a person will see when they encounter your project, so it should be fairly brief but detailed. It will make your project stand out from a bunch of others.


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-03 20:01 UTC, BenMukebo commented on person.rb
>      @age = age
- [ ]  Great job 👏🏻 however, your code does not work as expected see the screenshot 👇🏻

![03ruby](https://user-images.githubusercontent.com/79058364/182697353-01c8a340-7af6-49e1-a7d2-03d021547a6e.png)

- Please make sure to add a descriptive README file, your README should have instructions on how to run your application locally

2022-08-03 22:00 UTC, ShahierNashaat requested changes
Hi @ahzamir, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
:heavy_check_mark: No Linter Error
:heavy_check_mark: Good Pull Request Description

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-03 22:00 UTC, ShahierNashaat commented on trimmer_decorator.rb
> +    @nameable.correct_name[0, 10] if @nameable.correct_name > 10
- [x] Kindly be noticed that you should compare the length of the string not the actual string.

```ruby
@nameable.correct_name[0, 10] if @nameable.correct_name.length > 10
```

2022-08-03 23:17 UTC, ahzamir commented on trimmer_decorator.rb
> +    @nameable.correct_name[0, 10] if @nameable.correct_name > 10
I solved it thank you very much

2022-08-03 23:19 UTC, keroloussamy approved these changes
Hi @ahzamir, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To highlight 🎯

- No linter errors.✔️
- Good code design and implementation. ✔️
- Add all the requirements. ✔️

![clap](https://media0.giphy.com/media/j2GPljpvL8Lulm3d0X/giphy.gif)

## Optional suggestions
_Check the comments under the review._

- [ ] x

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-04 07:37 UTC, ahzamir commented
@ShahierNashaat  @keroloussamy  @BenMukebo  Thank you very much for your kind review and feedback. 😊👍

2022-08-04 07:37 UTC, merged